import 'package:tes/models/Febri_chanel_model.dart';

List<ChanelModel> mdl = [
  ChanelModel(
    thum: "Tudia vs parkur",
    vidio: "l9AfUhruCPs",
    title: "PARKUR VS TUDIA LAGA MILLKYYY",
    desk: "Win mana",
    view: "99",
    like: "1M",
    subs: "3M",
    chname: "Milkyy",
    imgchn: "imgchn",
  ),ChanelModel(
    thum: "Bye ariana granat",
    vidio: "agneRtEe-t8",
    title: "",
    desk: "Ariana Grande - bye [Altare Remix]",
    view: "300k",
    like: "89k",
    subs: "1M",
    chname: "Altare",
    imgchn: "",
  ),ChanelModel(
    thum: "mukbang mura vs mehong",
    vidio: "2hK0cnKrG5o",
    title: "",
    desk: "Bandingin Ayam 5 Ribu sampe 1 Juta !",
    view: "99",
    like: "5",
    subs: "0",
    chname: "Rizly",
    imgchn: "",
  ),ChanelModel(
    thum: "",
    vidio: "",
    title: "",
    desk: "",
    view: "",
    like: "",
    subs: "",
    chname: "",
    imgchn: "",
  ),ChanelModel(
    thum: "",
    vidio: "",
    title: "",
    desk: "",
    view: "",
    like: "",
    subs: "",
    chname: "",
    imgchn: "",
  ),
];
