import 'package:tes/models/play_model.dart';

List<PlayModel> ll = [
  PlayModel(
    tittle: "Ruok full gameplay style thailand - Free Fire 31",
    views: "98K views",
    author: "Ruok",
    likes: "80K",
    thumbnailUrl: "assets/images/ruok.jpg",
    videoId: "FLXDQ4D5Ww4",
    tayang: "3.3M views",
    desk: "Ruok full gameplay style thailand #209 - Free Fire",
    chnName: "Ruok",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "Pes indonesia event terbaru",
    views: "98K views",
    author: "Pes Indonesian",
    likes: "80K",
    thumbnailUrl: "assets/images/pes.jpg",
    videoId: "MTEXgUp6owA",
    tayang: "3.9M views",
    desk:
        "VIDEO BIKIN NGAKAK!! UZUMAKI NEYMAR KUN !! SELEBRASI SPESIAL & TEMBAKAN RASENGAN SHURIKEN !!",
    chnName: "Ruok",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "Dave, Tems - Raindance (Lyrics)",
    views: "98K views",
    author: "Dave",
    likes: "80K",
    thumbnailUrl: "assets/images/raindance.jpg",
    videoId: "bhoybya39QU",
    tayang: "3.9M views",
    desk: "Dave, Tems - Raindance (Lyrics)",
    chnName: "Ruok",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle:
        "FUNKOT - MUTIARA [ADAKAH KENYAMANAN DIHATIMU] NEW 2025 BY DJ ALMIRA BERTO",
    views: "98K views",
    author: "Almira Berto",
    likes: "80K",
    thumbnailUrl: "assets/images/almira.jpg",
    videoId: "-BgcQudVhgM",
    tayang: "3.9M views",
    desk:
        "FUNKOT - MUTIARA [ADAKAH KENYAMANAN DIHATIMU] NEW 2025 BY DJ ALMIRA BERTO",
    chnName: "Almira Berto",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "MPL ID S17 | Regular Season Hari 3 Minggu 7 | Bahasa Indonesia",
    views: "98K views",
    author: "MPL INDONESIA",
    likes: "80K",
    thumbnailUrl: "assets/images/mpl.jpg",
    videoId: "BzpXLE1SR1s",
    tayang: "3.9M views",
    desk: "MPL ID S17 | Regular Season Hari 3 Minggu 7 | Bahasa Indonesia",
    chnName: "MPL",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle:
        "Sean Paul - Give It Up To Me (feat. Keyshia Cole) [Official Video]",
    views: "1M views",
    author: "Sean  Paul",
    likes: "100K",
    thumbnailUrl: "assets/images/spul.jpg",
    videoId: "f84PvI_xe8k",
    tayang: "98k",
    desk: "when you gonna",
    chnName: "Lemes",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "WOWWWW belajar coding untuk pemula dijamin work no paswot",
    views: "200K view",
    author: "Kim Hasan",
    likes: "20K like",
    thumbnailUrl: "assets/images/blcd.jpg",
    videoId: "LooycZiMn6s",
    tayang: "10",
    desk: "tutorial coding untuk lu lu pada",
    chnName: "Kim Hasan",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "KICAUUUUUUUUUUUUUU",
    views: "2M",
    author: "BoyCord",
    likes: "2M",
    thumbnailUrl: "assets/images/kicau.jpg",
    videoId: "5k4llr0of_k",
    tayang: "2M",
    desk: "KICAU MANIA - NDARBOY GENK x BANDITOZ YAOW 86 (OFFICIAL LYRIC VIDEO) GAS POL NDANGAK",
    chnName: "Boy Cord Music",
    imgChn: "assets/images/gojo.jpg",
  ),
];
