import 'package:tes/models/play_model.dart';

List<PlayModel> ll = [
  PlayModel(
    tittle: "Ruok full gameplay style thailand - Free Fire 31",
    views: "98K views",
    likes: "80K",
    thumbnailUrl: "assets/images/ruok.jpg",
    videoId: "FLXDQ4D5Ww4",
    desk: "Ruok full gameplay style thailand #209 - Free Fire",
    chnName: "Ruok",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "Pes indonesia event terbaru",
    views: "12K views",
    likes: "80K",
    thumbnailUrl: "assets/images/pes.jpg",
    videoId: "MTEXgUp6owA",
    desk:
        "VIDEO BIKIN NGAKAK!! UZUMAKI NEYMAR KUN !! SELEBRASI SPESIAL & TEMBAKAN RASENGAN SHURIKEN !!",
    chnName: "Ruok",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "Dave, Tems - Raindance (Lyrics)",
    views: "900K views",
    likes: "80K",
    thumbnailUrl: "assets/images/raindance.jpg",
    videoId: "bhoybya39QU",
    desk: "Dave, Tems - Raindance (Lyrics)",
    chnName: "Ruok",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle:
        "FUNKOT - MUTIARA [ADAKAH KENYAMANAN DIHATIMU] NEW 2025 BY DJ ALMIRA BERTO",
    views: "18K views",
    likes: "80K",
    thumbnailUrl: "assets/images/almira.jpg",
    videoId: "-BgcQudVhgM",
    desk:
        "FUNKOT - MUTIARA [ADAKAH KENYAMANAN DIHATIMU] NEW 2025 BY DJ ALMIRA BERTO",
    chnName: "Almira Berto",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "MPL ID S17 | Regular Season Hari 3 Minggu 7 | Bahasa Indonesia",
    views: "1098 views",
    likes: "80K",
    thumbnailUrl: "assets/images/mpl.jpg",
    videoId: "BzpXLE1SR1s",
    desk: "MPL ID S17 | Regular Season Hari 3 Minggu 7 | Bahasa Indonesia",
    chnName: "MPL",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle:
        "Sean Paul - Give It Up To Me (feat. Keyshia Cole) [Official Video]",
    views: "1M views",
    likes: "100K",
    thumbnailUrl: "assets/images/spul.jpg",
    videoId: "f84PvI_xe8k",
    desk: "when you gonna",
    chnName: "Lemes",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "WOWWWW belajar coding untuk pemula dijamin work no paswot",
    views: "200K view",
    likes: "20K like",
    thumbnailUrl: "assets/images/blcd.jpg",
    videoId: "LooycZiMn6s",
    desk: "tutorial coding untuk lu lu pada",
    chnName: "Kim Hasan",
    imgChn: "assets/images/owo.jpg",
  ),
  PlayModel(
    tittle: "KICAUUUUUUUUUUUUUU",
    views: "2M",
    likes: "2M",
    thumbnailUrl: "assets/images/kicau.jpg",
    videoId: "5k4llr0of_k",
    desk:
        "KICAU MANIA - NDARBOY GENK x BANDITOZ YAOW 86 (OFFICIAL LYRIC VIDEO) GAS POL NDANGAK",
    chnName: "Boy Cord Music",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "AL-QURAN 30 juz",
    views: "3M",
    likes: "31K",
    thumbnailUrl: "assets/images/alquran.jpg",
    videoId: "xkuAToGvtW8",
    desk: "ALQURAN 30 JUZ FULL MERDU TANPA IKLAN",
    chnName: "Ustadz Hasan",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "BREAKBEAT BAILAR | BLACK HOLE SLOW REVERB LIRIK | REMIX DJ TELOOR",
    views: "1M",
    likes: "20K",
    thumbnailUrl: "assets/images/blackHole.jpg",
    videoId: "EpmpO8gkkaM",
    desk: "BREAKBEAT BAILAR | BLACK HOLE SLOW REVERB LIRIK | REMIX DJ TELOOR",
    chnName: "DJ TELOOR",
    imgChn: "assets/images/gojo.jpg",
  ),
  PlayModel(
    tittle: "alwys loving you",
    views: "300K",
    likes: "1M",
    thumbnailUrl: "assets/images/vvv.jpg",
    videoId: "Z4b8w2xNRlU",
    desk:
        "DJ ALWAYS LOVING YOU BREAKBEAT TERBARU 2024 BY DJ Herjuana | Slowed & Reverb",
    chnName: "DJ pinpin",
    imgChn: "imgChn",
  ),
];
